name: Github Pages

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/gh-pages.yml"
      - "docs/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: pip install sphinx git+https://github.com/Dog-Egg/sphinx-swaggerui.git -e .
      - run: sphinx-build -E -a -W -D html_baseurl="/${{ github.event.repository.name }}/" docs _site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
